Repository CharlSK8/Tienda-Facil, pull requests merged in 2024-11, with the labels that each got.

#2 docs: creacion del archivo README.md
  README.md
Labels: Blacklog

#4 Feature/swagger documentation
  pom.xml
  src/main/java/com/tienda/facil/core/config/SwaggerConfig.java
  src/main/java/com/tienda/facil/core/controller/TestController.java
  src/main/java/com/tienda/facil/core/dto/ResponseDTO.java
  src/main/java/com/tienda/facil/core/dto/TestDTO.java
  src/main/resources/application.properties
Labels: Done

#6 feat: creacion del docker-compose.yml
  docker/.env
  docker/docker-compose.yml
Labels: Done

#7 feat: implementación base de la funcionalidad "Crear Pedido" (Con…
  README.md
  src/main/java/com/tienda/facil/core/controller/PedidoController.java
  src/main/java/com/tienda/facil/core/data/LoaderData.java
  src/main/java/com/tienda/facil/core/dto/PedidoDto.java
  src/main/java/com/tienda/facil/core/dto/ResponseDTO.java
  src/main/java/com/tienda/facil/core/dto/TestDTO.java
  src/main/java/com/tienda/facil/core/model/ClienteModel.java
  src/main/java/com/tienda/facil/core/model/PedidoModel.java
  src/main/java/com/tienda/facil/core/model/PrioridadModel.java
  src/main/java/com/tienda/facil/core/repository/ClienteRepository.java
  src/main/java/com/tienda/facil/core/repository/PedidoRepository.java
  src/main/java/com/tienda/facil/core/repository/PrioridadRepository.java
  src/main/java/com/tienda/facil/core/service/PedidoService.java
  src/main/java/com/tienda/facil/core/utils/Constantes.java
  src/main/java/com/tienda/facil/core/utils/enums/EstadoActivo.java
  src/main/java/com/tienda/facil/core/utils/enums/EstadoPedido.java
  src/main/java/com/tienda/facil/core/utils/enums/MetodoPago.java
  src/main/java/com/tienda/facil/core/utils/enums/PrioridadPedido.java
  utils/guides/Como_trabajar_con_GitHub_y_Git_V1.pdf
  utils/guides/Como_usar_Trello_V1.pdf
Labels: In progress

#3 docs: creacion de archivo README.md
  README.md
  utils/guides/Como_trabajar_con_GitHub_y_Git_V1.pdf
  utils/guides/Como_usar_Trello_V1.pdf
Labels: In review

#10 feat: Implementacion completa de la funcionalidad del reporte de clie…
  pom.xml
  src/main/java/com/tienda/facil/core/controller/ClienteController.java
  src/main/java/com/tienda/facil/core/repository/ClienteRepository.java
  src/main/java/com/tienda/facil/core/service/ReportService.java
  src/main/resources/reports/clientesActivos.jrxml
Labels: In review

#11 Integración de login con pedidos y clientes
  docker/.env
  pom.xml
  src/main/java/com/tienda/facil/core/component/JwtAuthFilter.java
  src/main/java/com/tienda/facil/core/config/AppConfig.java
  src/main/java/com/tienda/facil/core/config/SecurityConfig.java
  src/main/java/com/tienda/facil/core/config/SwaggerConfig.java
  src/main/java/com/tienda/facil/core/controller/AuthController.java
  src/main/java/com/tienda/facil/core/controller/PedidoController.java
  src/main/java/com/tienda/facil/core/controller/TestController.java
  src/main/java/com/tienda/facil/core/dto/ResponseDTO.java
  src/main/java/com/tienda/facil/core/dto/request/ClienteRegisterRequestDTO.java
  src/main/java/com/tienda/facil/core/dto/request/LoginRequestDTO.java
  src/main/java/com/tienda/facil/core/dto/request/PedidoDto.java
  src/main/java/com/tienda/facil/core/dto/request/TestDTO.java
  src/main/java/com/tienda/facil/core/dto/response/ResponseDTO.java
  src/main/java/com/tienda/facil/core/dto/response/TokenResponse.java
  src/main/java/com/tienda/facil/core/exception/handler/ControllerAdvisor.java
  src/main/java/com/tienda/facil/core/mapper/IClienteMapper.java
  src/main/java/com/tienda/facil/core/model/Cliente.java
  src/main/java/com/tienda/facil/core/model/Token.java
  src/main/java/com/tienda/facil/core/repository/TokenRepository.java
  src/main/java/com/tienda/facil/core/repository/UserRepository.java
  src/main/java/com/tienda/facil/core/service/IAuthService.java
  src/main/java/com/tienda/facil/core/service/IJwtService.java
  src/main/java/com/tienda/facil/core/service/PedidoService.java
  src/main/java/com/tienda/facil/core/service/impl/AuthServiceImpl.java
  src/main/java/com/tienda/facil/core/service/impl/JwtService.java
  src/main/java/com/tienda/facil/core/util/constants/Constants.java
  src/main/java/com/tienda/facil/core/util/enums/Role.java
  src/main/java/com/tienda/facil/core/util/result/Result.java
  src/main/resources/application.properties
Labels: In review

#12 Integración de clientes y pedidos
  src/main/java/com/tienda/facil/core/component/JwtAuthFilter.java
  src/main/java/com/tienda/facil/core/config/AppConfig.java
  src/main/java/com/tienda/facil/core/config/SecurityConfig.java
  src/main/java/com/tienda/facil/core/controller/AuthController.java
  src/main/java/com/tienda/facil/core/controller/ClienteController.java
  src/main/java/com/tienda/facil/core/controller/PedidoController.java
  src/main/java/com/tienda/facil/core/data/LoaderData.java
  src/main/java/com/tienda/facil/core/dto/request/PedidoDto.java
  src/main/java/com/tienda/facil/core/model/Cliente.java
  src/main/java/com/tienda/facil/core/model/ClienteModel.java
  src/main/java/com/tienda/facil/core/model/Pedido.java
  src/main/java/com/tienda/facil/core/model/Prioridad.java
  src/main/java/com/tienda/facil/core/model/Token.java
  src/main/java/com/tienda/facil/core/repository/ClienteRepository.java
  src/main/java/com/tienda/facil/core/repository/PedidoRepository.java
  src/main/java/com/tienda/facil/core/repository/PrioridadRepository.java
  src/main/java/com/tienda/facil/core/repository/UserRepository.java
  src/main/java/com/tienda/facil/core/service/PedidoService.java
  src/main/java/com/tienda/facil/core/service/impl/AuthServiceImpl.java
  src/main/java/com/tienda/facil/core/util/constants/Constants.java
  src/main/java/com/tienda/facil/core/util/enums/EstadoActivo.java
  src/main/java/com/tienda/facil/core/util/enums/EstadoPedido.java
  src/main/java/com/tienda/facil/core/util/enums/MetodoPago.java
  src/main/java/com/tienda/facil/core/util/enums/PrioridadPedido.java
  src/main/java/com/tienda/facil/core/utils/Constantes.java
  src/main/resources/reports/clientesActivos.jrxml
Labels: Done

#13 Se crea controller para actualizar cliente y sus roles
  src/main/java/com/tienda/facil/core/config/SecurityConfig.java
  src/main/java/com/tienda/facil/core/controller/ClienteController.java
  src/main/java/com/tienda/facil/core/dto/request/ActualizarClienteRequestDTO.java
  src/main/java/com/tienda/facil/core/model/Cliente.java
  src/main/java/com/tienda/facil/core/service/IClienteService.java
  src/main/java/com/tienda/facil/core/service/ReportService.java
  src/main/java/com/tienda/facil/core/service/impl/ClienteServiceImpl.java
Labels: Done
